-- Snowflake infrastructure for the Olist delivery reliability analytics project.
-- Raw source tables were loaded into OLIST_ANALYTICS.RAW using Snowflake Snowsight.

USE ROLE SYSADMIN;

CREATE WAREHOUSE IF NOT EXISTS OLIST_WH
	WITH
		WAREHOUSE_SIZE = 'XSMALL'
		AUTO_SUSPEND = 60
		AUTO_RESUME = TRUE;

CREATE DATABASE IF NOT EXISTS OLIST_ANALYTICS;

CREATE SCHEMA IF NOT EXISTS OLIST_ANALYTICS.RAW;

USE WAREHOUSE OLIST_WH;
USE DATABASE OLIST_ANALYTICS;
USE SCHEMA RAW;