-- Read-only Snowflake access configuration for Tableau.
-- The Tableau role is intentionally limited to the curated dbt mart layer.

USE ROLE SECURITYADMIN;

CREATE ROLE IF NOT EXISTS TABLEAU_ROLE;

GRANT ROLE TABLEAU_ROLE
	TO ROLE SYSADMIN;


/*
Assign TABLEAU_ROLE to the appropriate analyst or BI user separately.

Example only:

GRANT ROLE TABLEAU_ROLE
	TO USER <TABLEAU_USER>;
*/


USE ROLE SYSADMIN;

GRANT USAGE
	ON WAREHOUSE OLIST_WH
	TO ROLE TABLEAU_ROLE;

GRANT USAGE
	ON DATABASE OLIST_ANALYTICS
	TO ROLE TABLEAU_ROLE;

GRANT USAGE
	ON SCHEMA OLIST_ANALYTICS.DBT_DEV_MARTS
	TO ROLE TABLEAU_ROLE;

GRANT SELECT
	ON ALL TABLES IN SCHEMA OLIST_ANALYTICS.DBT_DEV_MARTS
	TO ROLE TABLEAU_ROLE;

GRANT SELECT
	ON FUTURE TABLES IN SCHEMA OLIST_ANALYTICS.DBT_DEV_MARTS
	TO ROLE TABLEAU_ROLE;